name: Perplexed Polymath
favicon: null
layout_spectrum: 1
typography_spectrum: 0.327084707794711
title: Web home for Bob Schultz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#93cdf2'
    - '#ffffff'
    - '#2c86b3'
    - '#0f1b17'
    - '#626d49'
  brandStrength: 0.7233852006029338
  lightness: 0.6875
  saturation: 0.49380443478003144
  rhythmicContrast: 0.5
purpose: []
